services:
  - type: web
    name: learn-backend-api
    env: go
    rootDir: backend
    buildCommand: go build -o server main.go
    startCommand: ./server
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DB_HOST
        value: srv2113.hstgr.io
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: u721451974_lae
      - key: DB_PASSWORD
        value: "*Reedb4b4"
      - key: DB_NAME
        value: u721451974_lae_db
