services:
  - type: keyvalue
    name: game-redis-cache
    ipAllowList: []
    plan: free

  - type: web
    name: game-engine-service
    env: go
    rootDir: game_engine
    buildCommand: go build -o server main.go
    startCommand: ./server
    healthCheckPath: /api/v1/game/adventures
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DB_HOST
        value: srv2113.hstgr.io
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: u721451974_lae
      - key: DB_PASSWORD
        value: "*Reedb4b4"
      - key: DB_NAME
        value: u721451974_lae_db
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: game-redis-cache
          property: connectionString

  - type: web
    name: player-service
    env: go
    rootDir: player_service
    buildCommand: go build -o server main.go
    startCommand: ./server
    healthCheckPath: /api/v1/player/groups
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DB_HOST
        value: srv2113.hstgr.io
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: u721451974_lae
      - key: DB_PASSWORD
        value: "*Reedb4b4"
      - key: DB_NAME
        value: u721451974_lae_db
