import { LevelConfig, PathWaypoint } from '@/types/game';

// Exact Figma Percentage-Based Winding Board Game Path Waypoints matching maze.jpg
const FIGMA_MAZE_WAYPOINTS: PathWaypoint[] = [
  { index: 0, r: 0, c: 0, xPercent: 12, yPercent: 10, type: 'start', label: 'START' },
  { index: 1, r: 1, c: 0, xPercent: 12, yPercent: 22, type: 'normal' },
  { index: 2, r: 2, c: 0, xPercent: 12, yPercent: 34, type: 'normal' },
  { index: 3, r: 3, c: 0, xPercent: 12, yPercent: 46, type: 'normal' },
  { index: 4, r: 3, c: 1, xPercent: 25, yPercent: 46, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 5, r: 3, c: 2, xPercent: 38, yPercent: 46, type: 'coin', label: 'COIN' },
  { index: 6, r: 2, c: 2, xPercent: 38, yPercent: 34, type: 'normal' },
  { index: 7, r: 1, c: 2, xPercent: 38, yPercent: 22, type: 'normal' },
  { index: 8, r: 0, c: 2, xPercent: 38, yPercent: 10, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 9, r: 0, c: 3, xPercent: 50, yPercent: 10, type: 'normal' },
  { index: 10, r: 0, c: 4, xPercent: 62, yPercent: 10, type: 'normal' },
  { index: 11, r: 0, c: 5, xPercent: 75, yPercent: 10, type: 'normal' },
  { index: 12, r: 0, c: 6, xPercent: 88, yPercent: 10, type: 'normal' },
  { index: 13, r: 1, c: 6, xPercent: 88, yPercent: 22, type: 'coin', label: 'COIN' },
  { index: 14, r: 2, c: 6, xPercent: 88, yPercent: 34, type: 'normal' },
  { index: 15, r: 3, c: 6, xPercent: 88, yPercent: 46, type: 'normal' },
  { index: 16, r: 4, c: 6, xPercent: 88, yPercent: 58, type: 'star', effect: 'advance_3', label: 'ADVANCE 3 SPACES' },
  { index: 17, r: 5, c: 6, xPercent: 88, yPercent: 70, type: 'normal' },
  { index: 18, r: 6, c: 6, xPercent: 88, yPercent: 82, type: 'normal' },
  { index: 19, r: 7, c: 6, xPercent: 88, yPercent: 92, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 20, r: 7, c: 5, xPercent: 75, yPercent: 92, type: 'coin', label: 'COIN' },
  { index: 21, r: 7, c: 4, xPercent: 62, yPercent: 92, type: 'normal' },
  { index: 22, r: 6, c: 4, xPercent: 62, yPercent: 80, type: 'coin', label: 'COIN' },
  { index: 23, r: 5, c: 4, xPercent: 62, yPercent: 68, type: 'normal' },
  { index: 24, r: 4, c: 4, xPercent: 62, yPercent: 56, type: 'normal' },
  { index: 25, r: 4, c: 3, xPercent: 50, yPercent: 56, type: 'star', effect: 'advance_3', label: 'ADVANCE 3 SPACES' },
  { index: 26, r: 4, c: 2, xPercent: 38, yPercent: 56, type: 'normal' },
  { index: 27, r: 5, c: 2, xPercent: 38, yPercent: 68, type: 'normal' },
  { index: 28, r: 6, c: 2, xPercent: 38, yPercent: 80, type: 'coin', label: 'COIN' },
  { index: 29, r: 6, c: 1, xPercent: 25, yPercent: 80, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 30, r: 6, c: 0, xPercent: 12, yPercent: 80, type: 'coin', label: 'COIN' },
  { index: 31, r: 7, c: 0, xPercent: 12, yPercent: 92, type: 'normal' },
  { index: 32, r: 7, c: 1, xPercent: 25, yPercent: 92, type: 'normal' },
  { index: 33, r: 7, c: 2, xPercent: 38, yPercent: 92, type: 'normal' },
  { index: 34, r: 7, c: 3, xPercent: 50, yPercent: 92, type: 'goal', label: 'FINISH' },
];

export const PUZZLE_LEVELS: LevelConfig[] = [
  {
    id: 1,
    title: 'Custom Figma Board Engine',
    subtitle: 'Figma Image Background + Tile Logic Triggers',
    description: 'Design your maze artwork in Figma, export as PNG/SVG, and place waypoints anywhere! As your 3D explorer steps on tiles, code logic triggers coins, stars (+3), shells (-2), and victory!',
    bgImage: '/maze.jpg', // User's Figma design export image!
    waypoints: FIGMA_MAZE_WAYPOINTS,
    availableBlocks: ['move_forward', 'repeat', 'say_hello', 'play_sound'],
    maxBlocks: 12,
  },
  {
    id: 2,
    title: 'Figma Calibration & Test Board',
    subtitle: 'Interactive Coordinate Mapper Mode',
    description: 'Use the interactive Calibration Tool to click anywhere on your custom Figma maze design to grab exact (x%, y%) coordinates!',
    bgImage: '/maze.jpg',
    waypoints: FIGMA_MAZE_WAYPOINTS,
    availableBlocks: ['move_forward', 'repeat', 'say_hello', 'play_sound'],
    maxBlocks: 10,
  },
];
