import { LevelConfig, PathWaypoint, AdventureConfig } from '@/types/game';

// Level 1 specific track waypoints (4-tile straight vertical axis in center of Level 1 SVG, FINISH on tile 4)
export const LEVEL_1_WAYPOINTS: PathWaypoint[] = [
  { index: 0, r: 0, c: 0, xPercent: 50.16, yPercent: 37.6, type: 'start', label: 'START' },
  { index: 1, r: 1, c: 0, xPercent: 50.16, yPercent: 46.0, type: 'normal' },
  { index: 2, r: 2, c: 0, xPercent: 50.16, yPercent: 54.5, type: 'normal' },
  { index: 3, r: 3, c: 0, xPercent: 50.16, yPercent: 63.0, type: 'goal', label: 'FINISH' },
];

// Level 2 specific track waypoints (straight vertical axis in center of Level 2 SVG)
export const LEVEL_2_WAYPOINTS: PathWaypoint[] = [
  { index: 0, r: 0, c: 0, xPercent: 49.44, yPercent: 35.7, type: 'start', label: 'START' },
  { index: 1, r: 1, c: 0, xPercent: 49.44, yPercent: 42.4, type: 'normal' },
  { index: 2, r: 2, c: 0, xPercent: 49.44, yPercent: 49.1, type: 'normal' },
  { index: 3, r: 3, c: 0, xPercent: 49.44, yPercent: 55.8, type: 'normal' },
  { index: 4, r: 4, c: 0, xPercent: 49.44, yPercent: 62.5, type: 'normal' },
  { index: 5, r: 5, c: 0, xPercent: 49.44, yPercent: 69.2, type: 'goal', label: 'FINISH' },
];

// Shared Waypoints matching maze path layout
const DEFAULT_WAYPOINTS: PathWaypoint[] = [
  { index: 0, r: 0, c: 0, xPercent: 12, yPercent: 10, type: 'start', label: 'START' },
  { index: 1, r: 1, c: 0, xPercent: 12, yPercent: 22, type: 'normal' },
  { index: 2, r: 2, c: 0, xPercent: 12, yPercent: 34, type: 'normal' },
  { index: 3, r: 3, c: 0, xPercent: 12, yPercent: 46, type: 'normal' },
  { index: 4, r: 3, c: 1, xPercent: 25, yPercent: 46, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 5, r: 3, c: 2, xPercent: 38, yPercent: 46, type: 'coin', label: 'COIN' },
  { index: 6, r: 2, c: 2, xPercent: 38, yPercent: 34, type: 'normal' },
  { index: 7, r: 1, c: 2, xPercent: 38, yPercent: 22, type: 'normal' },
  { index: 8, r: 0, c: 2, xPercent: 38, yPercent: 10, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 9, r: 0, c: 3, xPercent: 50, yPercent: 10, type: 'normal' },
  { index: 10, r: 0, c: 4, xPercent: 62, yPercent: 10, type: 'normal' },
  { index: 11, r: 0, c: 5, xPercent: 75, yPercent: 10, type: 'normal' },
  { index: 12, r: 0, c: 6, xPercent: 88, yPercent: 10, type: 'normal' },
  { index: 13, r: 1, c: 6, xPercent: 88, yPercent: 22, type: 'coin', label: 'COIN' },
  { index: 14, r: 2, c: 6, xPercent: 88, yPercent: 34, type: 'normal' },
  { index: 15, r: 3, c: 6, xPercent: 88, yPercent: 46, type: 'normal' },
  { index: 16, r: 4, c: 6, xPercent: 88, yPercent: 58, type: 'star', effect: 'advance_3', label: 'ADVANCE 3 SPACES' },
  { index: 17, r: 5, c: 6, xPercent: 88, yPercent: 70, type: 'normal' },
  { index: 18, r: 6, c: 6, xPercent: 88, yPercent: 82, type: 'normal' },
  { index: 19, r: 7, c: 6, xPercent: 88, yPercent: 92, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 20, r: 7, c: 5, xPercent: 75, yPercent: 92, type: 'coin', label: 'COIN' },
  { index: 21, r: 7, c: 4, xPercent: 62, yPercent: 92, type: 'normal' },
  { index: 22, r: 6, c: 4, xPercent: 62, yPercent: 80, type: 'coin', label: 'COIN' },
  { index: 23, r: 5, c: 4, xPercent: 62, yPercent: 68, type: 'normal' },
  { index: 24, r: 4, c: 4, xPercent: 62, yPercent: 56, type: 'normal' },
  { index: 25, r: 4, c: 3, xPercent: 50, yPercent: 56, type: 'star', effect: 'advance_3', label: 'ADVANCE 3 SPACES' },
  { index: 26, r: 4, c: 2, xPercent: 38, yPercent: 56, type: 'normal' },
  { index: 27, r: 5, c: 2, xPercent: 38, yPercent: 68, type: 'normal' },
  { index: 28, r: 6, c: 2, xPercent: 38, yPercent: 80, type: 'coin', label: 'COIN' },
  { index: 29, r: 6, c: 1, xPercent: 25, yPercent: 80, type: 'shell', effect: 'back_2', label: 'GO BACK 2 SPACES' },
  { index: 30, r: 6, c: 0, xPercent: 12, yPercent: 80, type: 'coin', label: 'COIN' },
  { index: 31, r: 7, c: 0, xPercent: 12, yPercent: 92, type: 'normal' },
  { index: 32, r: 7, c: 1, xPercent: 25, yPercent: 92, type: 'normal' },
  { index: 33, r: 7, c: 2, xPercent: 38, yPercent: 92, type: 'normal' },
  { index: 34, r: 7, c: 3, xPercent: 50, yPercent: 92, type: 'goal', label: 'FINISH' },
];

export const ADVENTURE_1: AdventureConfig = {
  id: 1,
  slug: 'the-lost-monkey-explorer',
  title: 'The Lost Monkey Explorer',
  story: `A friendly little robot has crash-landed in the Whispering Forest. Its navigation system is broken, and only by giving it the correct instructions can it find its way home. Every level repairs a little more of the robot's memory and unlocks the path ahead.`,
  learningObjective: `Follow and create simple sequences; Understand that instructions execute in order; Navigate using movement commands; Plan a route before execution; Collect required items while completing a task; Recognize and avoid hazards; Debug simple mistakes; Complete increasingly complex algorithmic challenges.`,
  totalLevels: 12,
  levels: [
    {
      id: 1,
      levelNumber: 1,
      title: 'Power Up!',
      description: 'Learn that a robot only acts when given instructions.',
      objective: 'Learn that a robot only acts when given instructions.',
      mechanic: 'Basic movement (Move Forward)',
      bgImage: '/The Lost Monkey Explorer - Level 1.svg',
      waypoints: LEVEL_1_WAYPOINTS,
      availableBlocks: ['move_forward'],
      maxBlocks: 5,
    },
    {
      id: 2,
      levelNumber: 2,
      title: 'First Steps',
      description: 'Create a longer sequence of instructions.',
      objective: 'Create a longer sequence of instructions.',
      mechanic: 'Sequential execution',
      bgImage: '/The Lost Monkey Explorer - Level 2.svg',
      waypoints: LEVEL_2_WAYPOINTS,
      availableBlocks: ['move_forward'],
      maxBlocks: 8,
    },
    {
      id: 3,
      levelNumber: 3,
      title: 'Around the Tree',
      description: 'Navigate around an obstacle.',
      objective: 'Navigate around an obstacle.',
      mechanic: 'Turning (Left/Right)',
      bgImage: '/The Lost Monkey Explorer - Level 3.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right'],
      maxBlocks: 10,
    },
    {
      id: 4,
      levelNumber: 4,
      title: 'Energy Crystal',
      description: 'Collect your first item before reaching the goal.',
      objective: 'Collect your first item before reaching the goal.',
      mechanic: 'Collectibles',
      bgImage: '/The Lost Monkey Explorer - Level 4.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right'],
      maxBlocks: 10,
    },
    {
      id: 5,
      levelNumber: 5,
      title: 'Treasure Trail',
      description: 'Collect every energy crystal on the path.',
      objective: 'Collect every energy crystal on the path.',
      mechanic: 'Planning and multiple collectibles',
      bgImage: '/The Lost Monkey Explorer - Level 5.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 12,
    },
    {
      id: 6,
      levelNumber: 6,
      title: 'Danger Ahead',
      description: 'Reach the finish without touching dangerous tiles.',
      objective: 'Reach the finish without touching dangerous tiles.',
      mechanic: 'Hazard avoidance',
      bgImage: '/The Lost Monkey Explorer - Level 6.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 12,
    },
    {
      id: 7,
      levelNumber: 7,
      title: 'Watch Your Step!',
      description: 'Find a safe route around a pit.',
      objective: 'Find a safe route around a pit.',
      mechanic: 'Hazards and alternative paths',
      bgImage: '/The Lost Monkey Explorer - Level 7.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 12,
    },
    {
      id: 8,
      levelNumber: 8,
      title: 'Hidden Rewards',
      description: 'Explore to collect optional stars before finishing.',
      objective: 'Explore to collect optional stars before finishing.',
      mechanic: 'Exploration and bonus objectives',
      bgImage: '/The Lost Monkey Explorer - Level 8.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 15,
    },
    {
      id: 9,
      levelNumber: 9,
      title: 'Treasure Hunt',
      description: 'Collect all treasures and return safely to the finish.',
      objective: 'Collect all treasures and return safely to the finish.',
      mechanic: 'Exploration and route planning',
      bgImage: '/The Lost Monkey Explorer - Level 9.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 15,
    },
    {
      id: 10,
      levelNumber: 10,
      title: 'Choose Wisely',
      description: 'Find the safest and smartest path through the maze.',
      objective: 'Find the safest and smartest path through the maze.',
      mechanic: 'Decision making and optimization',
      bgImage: '/The Lost Monkey Explorer - Level 10.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 15,
    },
    {
      id: 11,
      levelNumber: 11,
      title: 'Explorer\'s Trial',
      description: 'Combine everything you\'ve learned to solve a complex maze.',
      objective: 'Combine everything you\'ve learned to solve a complex maze.',
      mechanic: 'Integrated sequencing, planning, and hazard avoidance',
      bgImage: '/The Lost Monkey Explorer - Level 11.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 20,
    },
    {
      id: 12,
      levelNumber: 12,
      title: 'Journey Home',
      description: 'Guide the robot through its final mission and help it return home.',
      objective: 'Guide the robot through its final mission and help it return home.',
      mechanic: 'Mastery challenge (all mechanics combined)',
      bgImage: '/The Lost Monkey Explorer - Level 12.svg',
      waypoints: DEFAULT_WAYPOINTS,
      availableBlocks: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
      maxBlocks: 25,
    },
  ],
};

export const PUZZLE_LEVELS: LevelConfig[] = ADVENTURE_1.levels;
